// make_golden.mjs — writes tests/ml/fixtures/heard-as-golden.json, the golden
// file of tests/ml/heard-as-equivalence-test.js.
//
//   node scripts/heard-as/make_golden.mjs        (needs the classifier in the transformers.js cache + python)
//
// For each committed lab fixture (public LibriSpeech, tests/resonance-lab/fixtures/,
// upsampled to 48 kHz): the production chain (chain.mjs) -> the scored windows
// [audioMs, logit | null, mode, classified 0/1] (the classifier runs every
// ML_CLASSIFY_HOP_MS; skipped windows carry no logit) and the posted pitch
// [audioMs, f0]; then
// scripts/heard-as/golden_check.py computes meterLogit, lnF0 and the shares
// under the shipped constants INDEPENDENTLY (plain Python, its own reading of
// the definition) and writes them into the file. The test then requires
// src/ml/heard-as.js to reproduce them (1e-9 / 1e-12) and the chain to
// reproduce the window set and pitch exactly.
//
// Re-run after ANY change to the utterance gate, the pitch chain or
// decideMlWindow — and re-check (or refit) the heard-as constants first:
// measurements/heard-as-calibration-2026-10-07.md.

import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { replay, loadClassifier, readWav16, upsample16to48 } from "./chain.mjs";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const { HEARD_AS_CALIBRATION: C } = await import(pathToFileURL(path.join(repo, "src/ml/heardAsCalibration.js")).href);
const score = await loadClassifier();
if (!score) { console.error("classifier not in the transformers.js cache"); process.exit(2); }
const out = {
  note: "Generated by scripts/heard-as/make_golden.mjs; aggregates by scripts/heard-as/golden_check.py. Public LibriSpeech fixtures (CC BY 4.0).",
  constants: { a: C.a, bMeter: C.bMeter, bLnF0: C.bLnF0, halfWidth: C.halfWidth, unsureK: C.unsureK, unsureFloor: C.unsureFloor },
  mlWindowMs: 750,
  fixtures: {},
};
for (const name of ["ls_woman_high", "ls_man_low", "ls_man_hi8_f105"]) {
  const { x } = readWav16(readFileSync(path.join(repo, "tests/resonance-lab/fixtures", `${name}.wav`)));
  const y = await upsample16to48(x);
  const r = await replay(y, { sr: 48000 });
  const windows = [];
  for (const w of r.windows) windows.push([w.audioMs, w.classify ? await score(w.win) : null, w.mode, w.classify ? 1 : 0]);
  out.fixtures[name] = { windows, pitch: r.pitch };
  console.log(`${name}: ${windows.length} scored windows (${windows.filter((w) => w[3]).length} classified), ${r.pitch.length} pitch frames`);
}
const tmp = path.join(repo, "build", "heard-as-golden.tmp.json");
writeFileSync(tmp, JSON.stringify(out));
const py = spawnSync(process.env.PYTHON ?? "python", [path.join(repo, "scripts/heard-as/golden_check.py"), tmp], { encoding: "utf8" });
if (py.status !== 0) { console.error(py.stdout, py.stderr); process.exit(1); }
const withPy = JSON.parse(readFileSync(tmp, "utf8"));
writeFileSync(path.join(repo, "tests/ml/fixtures/heard-as-golden.json"), JSON.stringify(withPy, null, 0) + "\n");
console.log(py.stdout.trim());
console.log("-> tests/ml/fixtures/heard-as-golden.json");
