# attribution.py — custom voice detector (2026-10-06): the attribution file
# for the CC BY / ODC-By training data of the released model (pre-registration
# §5 "Licence of the result": weights MIT, plus an attribution file built from
# the manifest), and the MIT licence text that goes next to the weights.
#
#   python attribution.py --out=build/vad-train/model [--tag=r2]   -> LICENSE, ATTRIBUTION.md
# Per CC BY clip: title, author, freesound.org/s/<id>/ link and the licence URL;
# per dataset: its licence link; plus a note of the changes made (2026-10-07,
# round-1 review). --tag=r2 adds the round-2 sources (Addendum D).
import collections
import os
import re

from tcommon import args, load_manifest

A = args()
MIT = """MIT License

Copyright (c) 2026 the Syrinx contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


LIC_URL = {"CC BY 4.0": "https://creativecommons.org/licenses/by/4.0/", "CC BY 3.0": "https://creativecommons.org/licenses/by/3.0/",
           "CC0 1.0": "https://creativecommons.org/publicdomain/zero/1.0/"}
R1_SOURCES = {"librispeech", "vctk", "coswara", "mdvr", "dcs", "esmuc", "csd", "fsd50k", "fstrain"}
R2_SOURCES = {"svd", "singbap", "imitations", "kids", "fsvoice"}
FREESOUND = ("fsd50k", "fstrain", "fsvoice")
NL = chr(10)
CHANGES = ("Changes: every recording was converted to mono, resampled to 16 kHz, cut into excerpts, level-scaled, filtered, "
           "reverberated and mixed with other recordings, and used only to train the model. The model's weights do not "
           "contain the audio.")


def title_of(r):
    if r.get("title"):
        return r["title"]
    m = re.match(r'^"(.*)" by ', r.get("attribution") or "", re.S)
    return m.group(1) if m else None


def main():
    out = A.get("out", "build/vad-train/model")
    tag = A.get("tag", "")
    srcs = R1_SOURCES | (R2_SOURCES if tag == "r2" else set())
    os.makedirs(out, exist_ok=True)
    man = load_manifest()
    tr = [r for r in man.values() if not r.get("drop") and r["split"] == "train" and r["source"] in srcs]
    L = ["# Training-data attribution — Syrinx custom voice detector", "",
         "The model weights are released under the MIT licence (LICENSE). They were trained on the",
         "openly licensed audio below (training split only; no NC / ND / ShareAlike material).",
         "Synthetic interferers and room impulse responses were generated by this project's own code.", "",
         CHANGES, "",
         "Licences: " + "; ".join(f"{k} — {v}" for k, v in LIC_URL.items()) + ".", ""]
    by = collections.defaultdict(list)
    for r in tr:
        by[r["source"]].append(r)
    L.append("## Datasets" + NL)
    L.append("| source | files | licence(s) | attribution |")
    L.append("|---|---|---|---|")
    for src, rs in sorted(by.items()):
        lic = collections.Counter(r["licence"] for r in rs)
        if src in FREESOUND:
            attr = {"fsd50k": "Freesound users (per clip, below); FSD50K, E. Fonseca et al., zenodo 4060432 (https://zenodo.org/records/4060432), CC BY 4.0",
                    "fstrain": "Freesound users (per clip, below)", "fsvoice": "Freesound users (per clip, below)"}[src]
        else:
            attr = rs[0].get("attribution")
        L.append(f"| {src} | {len(rs)} | {', '.join(f'[{k}]({LIC_URL.get(k, k)}) ({v})' for k, v in lic.most_common())} | {attr} |")
    L.append(NL + "## Freesound clips under CC BY (per clip: title, author, link, licence)" + NL)
    ups = collections.defaultdict(list)
    for src in FREESOUND:
        for r in by.get(src, []):
            if r["licence"].startswith("CC BY"):
                ups[r.get("uploader") or r["group"].split(":", 1)[1]].append((int(r["freesound_id"]), title_of(r), r["licence"]))
    for u in sorted(ups, key=str.lower):
        L.append(f"- **{u}**:")
        for i, t, lc in sorted(ups[u]):
            tt = (t or "untitled").replace(NL, " ").replace("|", "/")
            L.append(f"  - \"{tt}\" — https://freesound.org/s/{i}/ — [{lc}]({LIC_URL.get(lc, lc)})")
    L.append(NL + f"({sum(len(v) for v in ups.values())} CC BY clips by {len(ups)} uploaders. CC0 clips need no attribution and are not listed.)")
    with open(os.path.join(out, "ATTRIBUTION.md"), "w", encoding="utf8") as f:
        f.write(NL.join(L) + NL)
    with open(os.path.join(out, "LICENSE"), "w", encoding="utf8") as f:
        f.write(MIT)
    print(f"{out}: LICENSE, ATTRIBUTION.md ({len(tr)} training files, {len(ups)} CC BY uploaders, sources {sorted(by)})")


if __name__ == "__main__":
    main()
