# attribution.py — custom voice detector (2026-10-06): the attribution file
# for the CC BY / ODC-By training data of the released model (pre-registration
# §5 "Licence of the result": weights MIT, plus an attribution file built from
# the manifest), and the MIT licence text that goes next to the weights.
#
#   python attribution.py --out=build/vad-train/model    -> LICENSE, ATTRIBUTION.md
import collections
import os

from tcommon import args, load_manifest

A = args()
MIT = """MIT License

Copyright (c) 2026 the Syrinx contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


def main():
    out = A.get("out", "build/vad-train/model")
    os.makedirs(out, exist_ok=True)
    man = load_manifest()
    tr = [r for r in man.values() if not r.get("drop") and r["split"] == "train"]
    L = ["# Training-data attribution — Syrinx custom voice detector", "",
         "The model weights are released under the MIT licence (LICENSE). They were trained on the",
         "openly licensed audio below (training split only; no NC / ND / ShareAlike material).",
         "Synthetic interferers and room impulse responses were generated by this project's own code.", ""]
    by = collections.defaultdict(list)
    for r in tr:
        by[r["source"]].append(r)
    L.append("## Datasets\n")
    L.append("| source | files | licence(s) | attribution |")
    L.append("|---|---|---|---|")
    for src, rs in sorted(by.items()):
        lic = collections.Counter(r["licence"] for r in rs)
        attr = rs[0].get("attribution") if src not in ("fsd50k", "fstrain") else (
            "Freesound users (per clip, below); FSD50K (Fonseca et al., zenodo 4060432, CC BY 4.0)" if src == "fsd50k" else "Freesound users (per clip, below)")
        L.append(f"| {src} | {len(rs)} | {', '.join(f'{k} ({v})' for k, v in lic.most_common())} | {attr} |")
    L.append("\n## Freesound clips under CC BY (credit per uploader)\n")
    ups = collections.defaultdict(list)
    for src in ("fsd50k", "fstrain"):
        for r in by.get(src, []):
            if r["licence"].startswith("CC BY"):
                ups[r.get("uploader") or r["group"].split(":", 1)[1]].append((r["freesound_id"], r["licence"]))
    for u in sorted(ups, key=str.lower):
        ids = sorted(ups[u])
        L.append(f"- **{u}**: " + ", ".join(f"freesound.org/s/{i}/ ({lc})" for i, lc in ids))
    L.append(f"\n({sum(len(v) for v in ups.values())} CC BY clips by {len(ups)} uploaders; CC0 clips need no attribution and are not listed.)")
    with open(os.path.join(out, "ATTRIBUTION.md"), "w", encoding="utf8") as f:
        f.write("\n".join(L) + "\n")
    with open(os.path.join(out, "LICENSE"), "w", encoding="utf8") as f:
        f.write(MIT)
    print(f"{out}: LICENSE, ATTRIBUTION.md ({len(tr)} training files, {len(ups)} CC BY uploaders)")


if __name__ == "__main__":
    main()
